### PR TITLE
remove no skipped tests

### PR DESCRIPTION
**Pull request by veritem**

### CODE REVIEW

**Comment by KoenBrouwer** [comment]
@veritem Hi, why is this rule removed?

**Comment by veritem** [comment]
@KoenBrouwer  this was a duplicate, there is an another one called disabled tests

**Comment by KoenBrouwer** [comment]
@veritem Ah ok, got it. I don't know how many people use this, but my stuff just broke because of this change, and there's no reference as to why such change was made. It would be great if you could document changes like this. Thanks! 👌🏻

**Comment by veritem** [comment]
I'm sorry to heat about this. I'll do my best to document this next time

**Pull request merged**
